#!/usr/bin/env python3
"""Build only generated public fixtures/downloads. No network or dependencies.

Run from any working directory. Outputs are replaced deliberately under dist/
and release/. Source files are never overwritten.
"""

from html.parser import HTMLParser
import json
import os
from pathlib import Path
import subprocess
import sys
import tomllib
from urllib.parse import unquote, urlsplit
import zipfile

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "dist"


class Page(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.refs = []
        self.ids = set()

    def handle_starttag(self, tag, attrs):
        attr = dict(attrs)
        if "id" in attr:
            if attr["id"] in self.ids:
                raise ValueError(f"duplicate HTML id: {attr['id']}")
            self.ids.add(attr["id"])
        for key in ("href", "src"):
            if attr.get(key):
                self.refs.append(attr[key])


def capture(kind):
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT / "src")
    proc = subprocess.run(
        [sys.executable, "-m", "envport", "doctor", "--demo", kind, "--format", "json"],
        cwd=ROOT, env=env, text=True, capture_output=True, timeout=30,
    )
    expected = 0 if kind == "good" else 1
    if proc.returncode != expected:
        raise RuntimeError(f"{kind} demo exit {proc.returncode}, expected {expected}: {proc.stderr}")
    data = json.loads(proc.stdout)
    if data["status"] != ("pass" if kind == "good" else "fail"):
        raise ValueError(f"unexpected demo status for {kind}")
    return data


def source_files():
    top = ["README.md", "PUBLISHING.md", "LICENSE", "CONTRIBUTING.md", "pyproject.toml", ".gitignore"]
    files = [ROOT / name for name in top]
    for folder in ("src", "tests", "examples", "scripts", ".github", "dist"):
        for path in sorted((ROOT / folder).rglob("*")):
            relative = path.relative_to(ROOT)
            if (not path.is_file() or path.is_symlink() or "__pycache__" in path.parts
                    or any(p.endswith(".egg-info") for p in path.parts)
                    or path.suffix in (".pyc", ".pyo", ".zip")
                    or "downloads" in relative.parts):
                continue
            files.append(path)
    return sorted(set(files))


def write_zip(target, files):
    target.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(target, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            archive.write(path, "envport/" + path.relative_to(ROOT).as_posix())
    with zipfile.ZipFile(target) as archive:
        if archive.testzip() is not None:
            raise ValueError(f"corrupt archive: {target}")


def validate_site():
    pages = {}
    for path in SITE.rglob("*.html"):
        parser = Page()
        parser.feed(path.read_text(encoding="utf-8"))
        pages[path.resolve()] = parser
    if not (SITE / "index.html").resolve() in pages:
        raise ValueError("dist/index.html is missing")
    for page, parser in pages.items():
        for ref in parser.refs:
            url = urlsplit(ref)
            if url.scheme or url.netloc:
                continue
            if url.path.startswith("/"):
                raise ValueError(f"root-relative URL breaks project Pages: {ref}")
            target = (page.parent / unquote(url.path)).resolve() if url.path else page
            if not target.is_relative_to(SITE.resolve()):
                raise ValueError(f"reference escapes dist: {ref}")
            if target.is_dir():
                target = target / "index.html"
            if not target.is_file():
                raise ValueError(f"missing local reference in {page.name}: {ref}")
            if url.fragment and target in pages and unquote(url.fragment) not in pages[target].ids:
                raise ValueError(f"missing fragment in {page.name}: {ref}")
    return len(pages)


def main():
    version = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]
    reports = {kind: capture(kind) for kind in ("good", "bad")}
    (SITE / "assets" / "demo-reports.js").write_text(
        "// Generated by scripts/build_release.py from actual CLI runs.\n"
        + "window.ENVPORT_DEMO_REPORTS = "
        + json.dumps(reports, ensure_ascii=True, indent=2, allow_nan=False) + ";\n",
        encoding="utf-8",
    )
    (SITE / "license.txt").write_text((ROOT / "LICENSE").read_text(encoding="utf-8"), encoding="utf-8")
    files = source_files()
    download = SITE / "downloads" / "envport-source.zip"
    write_zip(download, files)
    count = validate_site()
    release = ROOT / "release" / f"envport-{version}.zip"
    write_zip(release, files + [download])
    print(f"Validated {count} HTML pages and all local asset/fragment references.")
    print(f"Captured good={reports['good']['summary']}; bad={reports['bad']['summary']}.")
    print(f"Release: {release} ({release.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
